/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuctionsIndexImport } from './routes/auctions/index'
import { Route as AuctionsManageImport } from './routes/auctions/manage'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuctionsIndexRoute = AuctionsIndexImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRoute,
} as any)

const AuctionsManageRoute = AuctionsManageImport.update({
  id: '/auctions/manage',
  path: '/auctions/manage',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auctions/manage': {
      id: '/auctions/manage'
      path: '/auctions/manage'
      fullPath: '/auctions/manage'
      preLoaderRoute: typeof AuctionsManageImport
      parentRoute: typeof rootRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auctions/manage': typeof AuctionsManageRoute
  '/auctions': typeof AuctionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auctions/manage': typeof AuctionsManageRoute
  '/auctions': typeof AuctionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auctions/manage': typeof AuctionsManageRoute
  '/auctions/': typeof AuctionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions/manage' | '/auctions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions/manage' | '/auctions'
  id: '__root__' | '/' | '/auctions/manage' | '/auctions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuctionsManageRoute: typeof AuctionsManageRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuctionsManageRoute: AuctionsManageRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auctions/manage",
        "/auctions/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auctions/manage": {
      "filePath": "auctions/manage.tsx"
    },
    "/auctions/": {
      "filePath": "auctions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
