/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const AuctionsIndexLazyImport = createFileRoute("/auctions/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const AuctionsIndexLazyRoute = AuctionsIndexLazyImport.update({
	id: "/auctions/",
	path: "/auctions/",
	getParentRoute: () => rootRoute,
} as any).lazy(() =>
	import("./routes/auctions/index.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/auctions/": {
			id: "/auctions/";
			path: "/auctions";
			fullPath: "/auctions";
			preLoaderRoute: typeof AuctionsIndexLazyImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexLazyRoute;
	"/auctions": typeof AuctionsIndexLazyRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexLazyRoute;
	"/auctions": typeof AuctionsIndexLazyRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexLazyRoute;
	"/auctions/": typeof AuctionsIndexLazyRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/auctions";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/auctions";
	id: "__root__" | "/" | "/auctions/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute;
	AuctionsIndexLazyRoute: typeof AuctionsIndexLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	AuctionsIndexLazyRoute: AuctionsIndexLazyRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auctions/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auctions/": {
      "filePath": "auctions/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
